### ISSUE TITLE
GeoStyler assumes the path to start with /geoserver/

### ISSUE THREAD

**Issue by petersmythe** [geostyler/geostyler-geoserver-plugin#106]
Most GeoServer instances might be installed at, for example, http://localhost:8080/geoserver, but some are definitely not, they might be http://localhost:8080/my-path (or mapservice in the bottom screenshot)

GeoStyler installs properly and runs, but on the Style page, hangs with: GeoStyler is loading ...

![image](https://github.com/geostyler/geostyler-geoserver-plugin/assets/5699667/db4d274c-58da-4c37-b2fa-b7b47fd1d910)

In DevTools, I can see 2x 404 errors, because GeoStyler is trying to connect to GeoServer on the /geoserver/ path and not on the /my-path/ path.

![image](https://github.com/geostyler/geostyler-geoserver-plugin/assets/5699667/fa142ac7-caa9-42ed-9256-689b530d3171)

Before GeoStyler was extracted out of the GeoServer project it worked with a different path.  Is there a way to configure GeoStyler now?

**Comment by jansule** [comment]
@dnlkoch could you take a look at this?
