### ISSUE TITLE
Error when selecting option in "Change filter" menu

### ISSUE THREAD

**Issue by tkleinke** [geostyler/geostyler-geoserver-plugin#135]
It is currently not possible to switch to another filter type (AND, OR etc.). When selecting the respective dropdown menu option in the filter editor (e. g. "Change filter" -> "AND-Filter"), the input fields are replaced with the message "Unknown filter supplied":

<img width="945" alt="Geostyler Error" src="https://github.com/geostyler/geostyler-geoserver-plugin/assets/5707629/c6ffb2b0-ea1a-4391-bb2c-d0796e33a07d">

-----------------

After trying to switch filter types multiple times by selecting different options in the "Change filter" menu, sometimes another error appears (with error message "TypeError: undefined is not an object (evaluating 't[u].filter')" in console):

<img width="940" alt="Geostyler Error 2" src="https://github.com/geostyler/geostyler-geoserver-plugin/assets/5707629/91f21f55-87ef-4a2f-b3f6-a57821beb890">

-----------------

The Geostyler demo application doesn't show this behaviour, so it seems to me that it is a problem specific to the Geoserver plugin.

**Comment by jansule** [comment]
Thanks for the info @tkleinke. It looks like we have to update the GeoStyler version in the GeoServer plugin to the latest version.

**Comment by KaiVolland** [comment]
related to #137
