### ISSUE TITLE
geostyler geoserver plugin 1.3.0 / 1.3.2 does not start

### ISSUE THREAD

**Issue by wumpz** [geostyler/geostyler-geoserver-plugin#140]
* fresh war of GeoServer 2.51.1
* followed installation instructions (jar into web-inf/lib)

within the style window I see some GeoStyler is starting
using browser debugger I see some undefined useages within a forEach loop

**Comment by KaiVolland** [comment]
Please check out v1.3.1.

**Comment by wumpz** [comment]
Checked out version v1.3.2 but got another error:

```
wfsDataParser-ver-F01AD2C6AA7062E180003154A5AE61EE.js:2 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
(anonym) @ wfsDataParser-ver-F01AD2C6AA7062E180003154A5AE61EE.js:2
org.geoserver.wms.we…ata.StyleEditPage:1 Uncaught (in promise) Could not parse XML document: TypeError: Cannot read properties of undefined (reading 'element')
```

Maybe it has to do with other plugins like ysld, CSS plugins, ... installed?

Tested on Chrome and Edge (same engine --> same problem).

**Comment by wumpz** [comment]
To be complete, I have tested this with a GeoServer including these plugins:
* CSS - Plugin
* SqlServer - Plugin
* WPS - Plugin
* Charts - Plugin
* App-Schema - Plugin
* YSLD - Plugin
* Inspire - Plugin

all matching with GeoServer Version 2.25.1.

**Comment by KaiVolland** [comment]
Hmm okay. I'll give this another try in the next days. Latest at the Codesprint next week.

**Comment by KaiVolland** [comment]
I debug a bit into it and i guess the error `org.geoserver.wms.we…ata.StyleEditPage:1 Uncaught (in promise) Could not parse XML document: TypeError: Cannot read properties of undefined (reading 'element')` is related to [this part of the wfs-parser](https://github.com/geostyler/geostyler-wfs-parser/blob/main/src/WfsDataParser.ts#L192).

I created a PR to make this more failsafe: https://github.com/geostyler/geostyler-wfs-parser/pull/588

I'll create a new release of the plugin once the wfs parser is updated.

**Comment by wumpz** [comment]
@KaiVolland Now GeoStyler starts. However, I have some remarks:
* GeoStyler starts for CSS, YSLD styles as well. If you press *Add Rule* you overwrite the whole style with some SLD stuff
* ![image](https://github.com/geostyler/geostyler-geoserver-plugin/assets/1569337/f8392f66-b407-4793-859c-90d064097b57) 
   til now I had no meaningful filter extraction from my slds. The corresponding filter from sld is
```xml
<ogc:Filter>
             <And>
            <ogc:PropertyIsEqualTo>
              <ogc:Function name="dimension">
                <ogc:Function name="geometry"/>
              </ogc:Function>
              <ogc:Literal>0</ogc:Literal>
            </ogc:PropertyIsEqualTo>
             <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>schadensbewertung</ogc:PropertyName>
              <ogc:Literal>3</ogc:Literal>
            </ogc:PropertyIsEqualTo>  
            </And>
          </ogc:Filter>
´´´

**Comment by KaiVolland** [comment]
This is indeed a problem. I created a new issue as this is a diffrent topic: #156
